### ISSUE TITLE
can update this project version in rubygems?

### ISSUE THREAD

**Issue by ywjno** [tispratik/bootstrap-timepicker-rails#13]
The project code has `removed dependency on less` in #10, but with I install this gem form rubygems, it also is 0.1.2 version.

So can update this gem in rubygems?

**Comment by felipecm** [comment]
please update the rubygems. This is causing deploy issues with Amazon ElasticBeanstalk.

**Comment by JoshuaNovak919** [comment]
+1

**Comment by tispratik** [comment]
Released new gem.

**Comment by ywjno** [comment]
Thank you very much. I'll close this issue.
