### ISSUE TITLE
Time selector "modal" not appearing

### ISSUE THREAD

**Issue by DevanB** [tispratik/bootstrap-timepicker-rails#15]
I am having an issue where the actual way to select the time is not showing up. I can tell that the javascript is in effect, because after I de-select the box, the time jumps to 12:00AM (the default I'm guessing). Any ideas what could cause it to be working, but not showing itself?

![screen shot 2013-07-17 at 9 33 13 am](https://f.cloud.github.com/assets/354652/812329/d872ab0c-eeed-11e2-9c52-f43a15545711.png)

**Comment by geoffw8** [comment]
Hey. This is happening for me too. Literally exact same thing... Am using SimpleForm in case that helps.

**Comment by DevanB** [comment]
I'm using simple_form as well. Any luck so far?

**Comment by geoffw8** [comment]
Devan  

Not from me I'm afraid. I did try another picker, and had EXACTLY the same result, though. Not sure why, I'm also using the date picker gem too, are you? I wonder if there is a conflict…

Geoff  

## 

Geoff Wright
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by DevanB** [comment]
I'm using the date picker gem as well. I tried both the bootstrap-rails-timepicker and the bootstrap-rails-timepicker-addon, but no luck. I also removed the date picker and tried the time picker, but not luck there also. I may just try a .js file directly. Hate to see the gem not work though.

-Devan

**Comment by cj3kim** [comment]
I'm experiencing the same issue. :[

**Comment by frahugo** [comment]
I had a similar issue, but with the 'dropdown' template (the default one).  The parent element requires the class 'bootstrap-timepicker' for the time widget to show up.  This is used by the CSS code to position the widget.

**Comment by davycardinaal** [comment]
+1 @frahugo

**Comment by frahugo** [comment]
I fixed the bug in bootstrap-timepicker (see https://github.com/jdewit/bootstrap-timepicker/pull/164) and my change is available in the latest version of bootstrap-timepicker.

We would need to get the latest version from bootstrap-timepicker, but I see that some changes were done locally in this gem, such as the glyphicon stuff.  What do we do?  If bootstrap-timepicker-rails is meant to be as asset pipeline wrapper, I think we should not modify the original source code.
