### ISSUE TITLE
File not found after bundle install

### ISSUE THREAD

**Issue by dalison** [tispratik/bootstrap-timepicker-rails#8]
I tried following the documentation for installing this gem and get the following error after updating the Gemfile, application.css and application.js as directed:

couldn't find file 'bootstrap-timepicker'

This is coming from the application.css.

The bundle install worked cleanly. Not sure if there is another file dependency that is not documented.

**Comment by calebhaye** [comment]
Restart your web server.

**Comment by dalison** [comment]
That was indeed it. Thanks @calebhaye
